### ISSUE TITLE
Javascript API does not work with IE 9

### ISSUE THREAD

**Issue by san360** [PagerDuty/pdjs#6]
Hello ,

I am trying to access the pager duty using below code in IE9

 $(document).ready(function () {
            jQuery.ajax({
                url: "https://domain.pagerduty.com/api/v1/escalation_policies/on_call",
                type: "GET",
                contentType: 'application/json',
                dataType: 'json',
                crossDomain:true,
                headers: {
                    Authorization: 'Token token=uTzwrERtQ9NQz7wpXncu'
                },
                success: function (json) {
                    alert(json);
                }
            });

```
    });
```

However it does not work in IE 9 and gives Access is denied error.

Any suggestion please?

**Comment by davidski** [comment]
Just had this problem as well. I'm pretty sure this API library requires web sockets, which IE9 doesn't support. You'll need IE10+ or an alternative browser.

**Comment by thomblake** [comment]
Hi! Just hopping in to clean up some issues here. It looks like the code above isn't using the pdjs library, and if that's literally what you typed then `domain.pagerduty.com` _probably_ isn't a real domain.

Since this isn't a pdjs issue and it's pretty old, I'm closing it, but feel free to reach out to PD support if you're having issues with the API
